import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserContextProvider } from "./context/userContext";
import NavigationMenuBar from "./components/navBar";
import { CartProvider } from "./context/cartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://checkout.razorpay.com/v1/checkout.js" />
        <script src="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.js"></script>
      </head>
      <UserContextProvider>
        <CartProvider>
          <body className={inter.className}>
            <NavigationMenuBar />

            {children}
          </body>
        </CartProvider>
      </UserContextProvider>
    </html>
  );
}
